import { readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, extname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(here, '..');
const repoRoot = resolve(projectRoot, '../../..');
const distDir = resolve(projectRoot, 'dist');
const outPath = resolve(repoRoot, 'internal/server/annotation_runtime_generated.go');

const files = await readdir(distDir);
const jsName = files.find((file) => file === 'annotation.js');
const cssName = files.find((file) => file === 'annotation.css');

if (!jsName || !cssName) {
  throw new Error(`expected annotation.js and annotation.css in ${distDir}; found ${files.join(', ')}`);
}

const js = await readFile(resolve(distDir, jsName), 'utf8');
const css = await readFile(resolve(distDir, cssName), 'utf8');

const quote = (value) => JSON.stringify(value);
const go = `// Code generated by internal/runtime/annotation/scripts/build.mjs; DO NOT EDIT.

package server

const annotationRuntimeScript = ${quote(js)}

const annotationRuntimeStyle = ${quote(css)}

var annotationRuntimeAssets = map[string]runtimeAsset{
	"annotation.js":  {contentType: "text/javascript; charset=utf-8", body: annotationRuntimeScript},
	"annotation.css": {contentType: "text/css; charset=utf-8", body: annotationRuntimeStyle},
}
`;

await writeFile(outPath, go, 'utf8');
console.log(`wrote ${outPath} from ${distDir}`);
